# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_top_mlp_0_0/design_1_top_mlp_0_0.xci
# IP: The module: 'design_1_top_mlp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/ip/ila_0/ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# XDC: c:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc

# XDC: c:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_top_mlp_0_0/design_1_top_mlp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_mlp_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_top_mlp_0_0/design_1_top_mlp_0_0.xci
# IP: The module: 'design_1_top_mlp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/ip/ila_0/ila_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# XDC: c:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc

# XDC: c:/Users/sjh00/streamline/dsd_mlp.srcs/sources_1/bd/design_1/ip/design_1_top_mlp_0_0/design_1_top_mlp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_mlp_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
